version: '3.8'
services:
  landing:
    container_name: my_container_name
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - /app/.next
    ports:
      - 80:80
